name: Push to Dev Branch

on:
  push:
    branches: [ dev ]

env:
  PYTHON_VERSION: '3.10'

jobs:
  validate-dev:
    name: Validate Dev Branch
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check code formatting with Black
      run: black --check .

    - name: Run linting with Flake8
      run: flake8 .

    - name: Run all tests
      run: pytest -v

  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: validate-dev
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t my_project:dev-${{ github.sha }} .
        docker build -t my_project:dev-latest .

    - name: Test Docker image
      run: |
        docker run --rm -e USER_NAME=TestUser -e API_TOKEN=test123 my_project:dev-latest


